#pragma once

#include <QString>

/**
  * @brief This abstract class contains the family of hash algorithms,
  *        which generate int value by the string
  */
class HashFunction
{
public:
    HashFunction() {}
    virtual ~HashFunction() {}
    /**
      * @brief Method hashes the input string to the int value
      * @param[in] key Key string for hashing
      * @return unsigned int Hash generated by the key
      */
    virtual unsigned int hash(const QString& key) const = 0;
};

